
services:

  angular:
    image: angular.dev-image
    container_name: 'portfolio-frontend'
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 4200:4200
    volumes:
      - ./frontend/src:/app/src


  php:
    image: php-image
    container_name: 'portfolio-backend'
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8080:80
    volumes:
      - ./backend:/var/www/html